In [6]:
import numpy as np

list1 = [11,22,33,44]
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
import numpy as np

list1 = [11,22,33,44]
a=np.array(list1)
print(a)

[11 22 33 44]


In [8]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [24]:
import numpy as np 

a = np.array(42) #0D
print(a)
print(a.ndim)
print(type(a))


42
0
<class 'numpy.ndarray'>


In [27]:
import numpy as np 

b = np.array([1,2,3,4,5])  #1D
print(b)
print(b.ndim)
print(type(b))


[1 2 3 4 5]
1
<class 'numpy.ndarray'>


In [26]:
import numpy as np 

c = np.array([[1,2,3],[5,6,7]])  #2D
print(c)
print(c.ndim)
print(type(c))


[[1 2 3]
 [5 6 7]]
2
<class 'numpy.ndarray'>


In [25]:
import numpy as np 

d = np.array([[[1,2,3],[5,6,7]],[[11,22,33],[24,56,78]]]) #3D
print(d)
print(d.ndim)
print(type(d))


[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [24 56 78]]]
3
<class 'numpy.ndarray'>


In [18]:
import numpy as np 

a = np.array(42) #0D
b = np.array([1,2,3,4,5])  #1D
c = np.array([[1,2,3],[5,6,7]])  #2D
d = np.array([[[1,2,3],[5,6,7]],[[11,22,33],[24,56,78]]]) #3D

print(a)
print(b)
print(c)
print(d)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



42
[1 2 3 4 5]
[[1 2 3]
 [5 6 7]]
[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [24 56 78]]]
0
1
2
3


In [30]:
import numpy as np 
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])


1
2
3
4


In [33]:
import numpy as np 
arr = np.array([1,2,3,4])
print(arr[0] + arr[1] )
print(arr[1] + arr[2] )
print(arr[2] + arr[3] )
print(arr[3] + arr[1] )

3
5
7
6


In [37]:
import numpy as np 
c = np.array([[1,2,3],[5,6,7]])  #2D
print("2nd element of 1st row : ",c[0,1])
print("2nd element of 2nd row : ",c[1,1])
print("Last element of 1st row : ",c[0,2])
print("Last element of 2nd row : ",c[1,2])

2nd element of 1st row :  2
2nd element of 2nd row :  6
Last element of 1st row :  3
Last element of 2nd row :  7


In [39]:
import numpy as np 
c = np.array([[1,2,3],[5,6,7]])  #2D
print(c[1,1] * c[0,1])
print(c[1,1] * c[0,2])
print(c[0,2] * c[1,2])
print(c[1,2] * c[1,1])


12
18
21
42


In [56]:
import numpy as np 
d = np.array([[[1,2,3],[5,6,7]],[[11,22,33],[24,56,78]]]) #3D
print(d[0,0,0])
print(d[0,0,1])
print(d[0,0,2])
print(d[0,1,0])
print(d[0,1,1])
print(d[0,1,2])
print(d[1,0,0])
print(d[1,0,1])
print(d[1,0,2])
print(d[1,1,0])
print(d[1,1,1])
print(d[1,1,2])


print(d[1,1,2] + d[1,1,1])
print(d[0,1,1] + d[1,0,2])
print(d[1,1,2] + d[0,0,2])

print(d[1,1,2] / d[1,1,1])
print(d[0,1,1] / d[1,0,2])
print(d[1,1,2] / d[0,0,2])

res = d[0,0,2] + d[0,1,2] + d[1,0,2] + d[1,1,2] 
print(res)

1
2
3
5
6
7
11
22
33
24
56
78
134
39
81
1.3928571428571428
0.18181818181818182
26.0
121
